kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
  namespace: kube-public
  labels:
    k8s-app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: react
    spec:
      containers:
        - name: react
          image: ccr.ccs.tencentyun.com/docschina/react:main-1706347153913
          resources: {}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeName: vm-12-17-opencloudos
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
