apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-8.3
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        args:
          - --lower_case_table_names=1
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --default-time-zone=+8:00
        image: mysql:8.3.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 4v@d10Uqg!Jh
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      nodeName: 111.229.109.39
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
          claimName: mysql-pvc
