apiVersion: v1
kind: Service
metadata: 
  name: docschina-api
  labels:
    app: docschina-api
spec:
  type: NodePort
  selector: 
    app:  docschina-api
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
      nodePort: 1337
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: docschina-api
  namespace: kube-public
  labels:
    k8s-app: docschina-api
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: docschina-api
  template:
    metadata:
      name: docschina-api
      creationTimestamp: null
      labels:
        k8s-app: docschina-api
    spec:
      containers:
        - name: docschina-api
          image: ccr.ccs.tencentyun.com/docschina/docschina-api:release-20240201-68c53bfe9f7463425c9f2ecd1f6028a692419811
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /data
            name: docschina-api-data
      nodeName: vm-12-17-opencloudos
      volumes:
        - name: docschina-api-data
          persistentVolumeClaim:
            claimName: docschina-api-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
